### ISSUE TITLE
Separate supported exchanges by features

### ISSUE THREAD

**Issue by sixels** [nash-io/openlimits#186]
It would be good to separate the exchanges by features. This would help if someone using the library don't want the Binance support, for example.

```toml
# Cargo.toml

[features]
binance = []
coinbase = []
```

Then lib.rs would be something like

```rust
// --snip--
#[cfg(feature = "binance")]
pub mod binance;
#[cfg(feature = "coinbase")]
pub mod coinbase;
```
